export default {
  altText: "Link button for ",
  linksToAdd: [
  ],
  linksToUpdate: [
  ],
  netizens: [
    { name: "Angel's Landing", url: "https://angelnetcast.com", src: "angelnetcast.gif", freezeframe: true },
    { name: "AntiKrist", url: "https://antikrist.lol", src: "antikrist.png" },
    { name: "arlita's internet page", url: "https://arlita.neocities.org", src: "arlita.gif" },
    { name: "Artwork", url: "https://artwork.neocities.org", src: "artwork.gif", freezeframe: true },
    { name: "Astrale Stella & Co", url: "https://astralestella.neocities.org", src: "astralestella.png" },
    { name: "Blink's Nest", url: "https://blinkmakesart.neocities.org/", noBtn: true },
    { name: "Bytemoth's Brook", url: "https://bytemoth.neocities.org", src: "bytemoth.png" },
    { name: "Captain's Undersea Blog", url: "https://captdedeyes.com", src: "captdedeyes.png" },
    { name: "catso club", url: "https://catso.club/", src: "catso.gif", freezeframe: true },
    { name: "Cherie", url: "https://cherie.nekoweb.org/", src: "cherie.gif" },
    { name: "Cinnamuff's Galaxy", url: "https://cinnamuff.space", src: "cinnamuff.png" },
    { name: "Cloud Cover", url: "https://cloudcover.neocities.org", src: "cloudcover.png" },
    { name: "Comfort's Bedroom", url: "https://comfort.kayla.care", src: "comfort.gif", freezeframe: true },
    { name: "Dannarchy", url: "https://dannarchy.com", src: "dannarchy.gif", freezeframe: true },
    { name: "daximus", url: "https://daximus.neocities.org", src: "daximus.gif", freezeframe: true },
    { name: "Dendrophalaen", url: "https://dendrophalaen.neocities.org/", src: "dendrophalaen.png" },
    { name: "Des", url: "https://des.neocities.org/", src: "des.gif", freezeframe: true },
    { name: "Dizzy's Bunny Hell", url: "https://doctordizzy.space", src: "doctordizzy.gif", freezeframe: true },
    { name: "Dolly Cuddles", url: "https://dollycuddles.neocities.org/", src: "dollycuddles.gif", freezeframe: true },
    { name: "Domain of the Grubby Dog", url: "https://your-local-grubdog.neocities.org/", src: "your-local-grubdog.png" },
    { name: "dusya ✿ dork", url: "https://dusyadork.neocities.org/", noBtn: "true" },
    { name: "Flower in Binary", url: "https://flowerinbinary.neocities.org", src: "flowerinbinary.png" },
    { name: "FoggyBear", url: "https://foggybear42.net/", src: "foggybear42.png" },
    { name: "Friend Shaped Plant", url: "https://friendshapedplant.neocities.org", src: "friendshapedplant.png" },
    { name: "Frills", url: "https://frills.dev", src: "frills.png" },
    { name: "Frog.net", url: "https://frognet.neocities.org/home", src: "frognet.gif", freezeframe: true },
    { name: "Gildedware", url: "https://gildedware.net", src: "gildedware.gif", freezeframe: true },
    { name: "Glamour Beast", url: "https://glamourbeast.neocities.org", src: "glamourbeast.png" },
    { name: "The Human Finny", url: "https://humanfinny.neocities.org", src: "humanfinny.gif", freezeframe: true },
    { name: "Jade Everstone", url: "https://jadeeverstone.com", src: "jadeeverstone.png" },
    { name: "jeith!", url: "https://jeith.com", src: "jeith.gif", freezeframe: true },
    { name: "Key's Klubhouse", url: "https://keysklubhouse.com", src: "keysklubhouse.png" },
    { name: "Kozel", url: "https://kozel.neocities.org", src: "https://kozel.neocities.org/Links/", noBtn: true },
    { name: "SPAAAAAAAAAACE", url: "https://kookoioi.neocities.org", src: "kookoioi.png" },
    { name: "kuroiOS", url: "https://kuroi.com.br/", src: "kuroios.png" },
    { name: "L-Chan's Website", url: "https://l-chan.neocities.org", src: "l-chan.png" },
    { name: "Lapis Label", url: "https://lapislabel.net", src: "lapislabel.png", freezeframe: true },
    { name: "Lazer Bunny's Website", url: "https://lazer-bunny.neocities.org", src: "lazer-bunny.gif", freezeframe: true },
    { name: "LHFM", url: "https://lhfm.neocities.org", src: "lhfm.png" },
    { name: "Linwood", url: "https://linwood.neocities.org", src: "linwood.gif", freezeframe: true },
    { name: "lizardmandan", url: "https://lizardmandan.neocities.org", src: "lizardmandan.gif", freezeframe: true },
    { name: "Lockheart Love", url: "https://lockheartlove.neocities.org", src: "lockheartlove.png" },
    { name: "Lost Letters", url: "https://lostletters.neocities.org", src: "lostletters.gif", freezeframe: true },
    { name: "Lugaw.gay", url: "https://lugaw.gay", src: "lugaw.png" },
    { name: "MakoEnergy.com", url: "https://makoenergy.neocities.org", src: "makoenergy.png" },
    { name: "Mizuki's World", url: "https://mizuki.world", src: "mizuki.gif", freezeframe: true },
    { name: "The Moon Palace", url: "https://mavisdeluna.art/", src: "mavisdeluna.gif", freezeframe: true },
    { name: "My Blace", url: "https://myblace.neocities.org", src: "myblace.png" },
    { name: "MystSaphyr", url: "https://mystsaphyr.art", src: "mystsaphyr.gif", freezeframe: true },
    { name: "Nathan's Space", url: "https://nathanntan.neocities.org/", src: "nathanntan.png" },
    { name: "Nickle's Faves", url: "https://nickle4apickle.neocities.org", src: "nickle4apickle.gif" },
    { name: "NomnomNami", url: "https://nomnomnami.com", src: "nomnomnami.gif", freezeframe: true },
    { name: "Nostalgic", url: "https://nostalgic.neocities.org", src: "nostalgic.gif" },
    { name: "Orion-Overdrive", url: "https://orion-overdrive.neocities.org/", src: "orion-overdrive.png" },
    { name: "PSSHAW", url: "https://psshaw.neocities.org", src: "psshaw.png" },
    { name: "Piranhebula", url: "https://piranhebula.neocities.org", src: "piranhebula.gif", freezeframe: true },
    { name: "The Pixeliana", url: "https://pixeliana.neocities.org", src: "pixeliana.gif", freezeframe: true },
    { name: "PKLucky's Beachside Lounge", url: "https://pklucky.neocities.org", src: "pklucky.gif", freezeframe: true },
    { name: "PolychromeXD", url: "https://polychromexd.neocities.org/", noBtn: true },
    { name: "Puruland", url: "https://purupurple.neocities.org", src: "purupurple.png" },
    { name: "SNK PLAYMOAR", url: "https://playmoar.neocities.org", src: "playmoar.gif" },
    { name: "QrunchySpace", url: "https://qrunchy.space/", src: "qrunchyspace.gif", freezeframe: true },
    { name: "Random Pixels", url: "http://digistar.db-destiny.net/rpixels/", src: "random-pixels.gif", freezeframe: true },
    { name: "RoseDryad", url: "https://rosedryad.com/", src: "rosedryad.gif", freezeframe: true },
    { name: "Sanguine Royal", url: "https://sanguineroyal.neocities.org", src: "sanguineroyal.gif", freezeframe: true },
    { name: "Seafare", url: "https://seafare.neocities.org", src: "seafare.png" },
    { name: "SkyKristal", url: "https://skykristal.art", src: "skykristal.png" },
    { name: "The Space Bar", url: "https://space-bar.neocities.org", src: "space-bar.gif", freezeframe: true },
    { name: "Strawberry Gashes", url: "https://strawberry-gashes.neocities.org/", src: "strawberry-gashes.gif" },
    { name: "The Absolute Realm", url: "https://theabsoluterealm.com", src: "theabsoluterealm.gif" },
    { name: "Themby", url: "https://themby.neocities.org", src: "themby.png" },
    { name: "ValyceNegative.it", url: "https://valycenegative.it", src: "valycenegative.gif" },
    { name: "THE WEBEVERSE", url: "https://webeverse.neocities.org/", src: "webeverse.png" },
    { name: "whiona.me", url: "https://whiona.me/", src: "whiona.png" },
    { name: "WiNGS.nu", url: "https://wings.nu", src: "wings.png" }
  ],
  resources: [
    {
      url: "https://kaomoji.ru/en",
      name: "Kaomoji: Japanese Emoticons",
      desc: "A large repository of adorable/kawaii text-based emoticons."
    },
    {
      url: "https://torcado.com/cleanEdge/",
      name: "cleanEdge",
      desc: "A tool to scale and rotate pixel art while still retaining clean edges."
    },
    {
      url: "https://waifu2x.udp.jp/",
      name: "waifu2x",
      desc: "A tool to upscale artwork that is otherwise pixelated or has too many JPG artifacts."
    },
    {
      url: "https://ezgif.com/",
      name: "Ezgif.com",
      desc: "A browser tool that allows users to do basic functions similar to art programs out there without actually downloading an art program. Includes resizing, cropping, animating GIFs, etc."
    },
    {
      url: "https://neonaut.neocities.org/brain/image-compression.html",
      name: "Neonaut: Become a Compression Sorcerer",
      desc: "A wonderful tutorial that provides tips on how to optimize images so that they still look nice but don't take 500 years to load."
    },
    {
      url: "https://htmlsymbols.xyz",
      name: "HTML Symbols",
      desc: "A repository of all (or at least most) HTML symbols that exist."
    },
    {
      url: "https://justtherecipe.com/",
      name: "Just The Recipe",
      desc: "A website that takes links of any recipe and removes all of the fluff and only leaves the recipe. Useful for when chefs force readers to scroll through 20+ pages just to get to the recipe."
    }
  ],
  credits: [
    { name: "Rina Cat's Domain", url: "http://web.archive.org/web/20041206135411/rinacat.com/main.html", desc: "inspiration" },
    { name: "Feather", url: "https://feathericons.com/", desc: "icons seen throughout the site" },
    { name: "Eleventy", url: "https://11ty.dev", desc: "static site generator" },
    { name: "Catppuccin", url: "https://catppuccin.com/", desc: "colors for RSS Feed and Rainbow clique on home page" },
    { name: "Bret Comnes", url: "https://github.com/marketplace/actions/deploy-to-neocities", desc: "deploy-to-neocities GitHub action" },
    { name: "Salma Alam-Naylor", url: "https://dev.to/whitep4nth3r/the-best-lightdark-mode-theme-toggle-in-javascript-368f", desc: "Light/dark mode toggle code inspiration" },
    { name: "Avi Aryan", url: "https://github.com/PrismJS/prism-themes/blob/master/themes/prism-ghcolors.css", desc: "GH Colors PrismJS theme with slight edits -light mode-" },
    { name: "Jared Jones and Simon Jespersen", url: "https://github.com/PrismJS/prism-themes/blob/master/themes/prism-laserwave.css", desc: "Laserwave PrismJS theme -dark mode-" }, { name: "**Viewers like you!**" }
  ]
}