export default [
  "the Internet fundamentally misunderstands your favorite character and it becomes the popular depiction.",
  "your closest friend in high school gets back in touch with you, arranges a hangout to talk and catch up. While you two have a fun couple of hours, I hope they try to sell you on an obvious MLM scam and get Karen-levels of upset when you politely turn them down.",
  "your marinara never sticks to your pasta.",
  "your friends always change the subject of their conversation when you enter the room but reassure you that you didn't miss anything.",
  "if you wear glasses, there's a small smudge on the lenses that cannot be cleared.",
  "your bones itch.",
  "all of your Hot Wheels are missing at least one wheel without rhyme or reason.",
  "all soups you make or order in the future have a faint bad metal taste.",
  "your sleeves roll down while you're washing your hands.",
  "your pillows are warm in the summer and cold in the winter.",
  "you remember that embarrassing thing you said right before you go to sleep tonight.",
  "whatever fandom you're in is overrun by cringe kids who don't understand inappropriate shipping, and that every time you tell someone you're in that fandom they look at you like you committed a crime.",
  "your monster husband gets turned into a marketable e-boy.",
  "the only water you find in a desert is from stepping in a puddle in your socks.",
  "the writers change your waifu/husbando for no reason so now you have to find a new one to love.",
  "your bread never toasts correctly.",
  "every book you read ends on a cliffhanger that's never mentioned in the following book.",
  "all cats hate you.",
  "your favorite game/movie/series receives a sequel, announced to be \"industry-defining\", then turns out to be a shell of what it once was, becoming a simple cash grab they will continue milking for the rest of time.",
  "Netflix makes a half-assed film adaptation of your favorite anime.",
  "that every shoe you put on has a thorn in the threading inside the sole. So when you pull it out it ruins the shoe, so you have to live with either the thorn digging into the bottom of your foot, or a hole in your shoe for other shit to get in.",
  "you never find a matching pair of socks in your drawer ever again.",
  "all of your popsicles have exactly one splinter in the stick.",
  "none of the clothes you buy fit exactly right, but not severely enough to where you can't wear it.",
  "your autosave corrupts.",
  "you get afflicted with an itch, and have no nails to scratch with.",
  "your waifu becomes a shit meme.",
  "your appliances never charge above 1%.",
  "you always feel like you're missing something crucial in your life, but never gain it, and never know just what that something is.",
  "all of your character arcs go unresolved.",
  "your favorite content creator gets included in a TV series and let all the fame get to their head until they're never the same.",
  "you have a lot of creative ideas, but never finish any of them to completion.",
  "your sleeves always get caught on door handles.",
  "your entire friend group gets into a series you can't stand.",
  "a fruitfly always annoys you, wherever you go.",
  "you forever feel the urge to sneeze, but you never do.",
  "your keyboard never reads every sixth input, but always reads every eleventh input twice.",
  "you never find the perfect shower temperature.",
  "you find what you need only after you no longer need it."
]